### PR TITLE
Update preprocessing.py

### PR DESCRIPTION
**Pull request by ozmig77**
If len(located_indices) is 0 and closest_1 is 0, located_indices may contain -1.

### CODE REVIEW

**Comment by jayleicn** [comment]
Hi @ozmig77 ,

Thanks for the pull request! Do you have statistics showing how often this happens?

**Comment by ozmig77** [comment]
Hi, as I count during running preprocessing.py,
tvqa_test_public : 58
tvqa_val : 106
tvqa_train : 1100
Thanks for reply.

**Comment by jayleicn** [comment]
Thanks!

**Comment by jayleicn** [comment]
@ozmig77 BTW does this fix improve the model's performance?

**Pull request merged**
